[mitsloan]
title = "Ideas and insight about artificial intelligence from MIT Sloan"
url = "https://mitsloan.mit.edu/ideas-made-to-matter/artificial-intelligence"
entrySelector = ".search-result--content"
titleSelector = ".search-result--title_link"
linkSelector = ".search-result--title_link"
